### ISSUE TITLE
Support of ActiveMQ queue statistics

### ISSUE THREAD

**Issue by ymitsos** [aparnachaudhary/nagios-plugin-jbossas7#10]
Hi,

check_queue_depth function fetches statistics from the /subsystem/messaging/hornetq-server/default/jms-queue/. If ActiveMQ is used, the aforementioned URL should be altered to /subsystem/messaging-activemq/server/default/jms-queue/

Does it make any sense for a PR?

**Comment by sgargel** [comment]
Hi @ymitsos ,
I think this repo is no longer maintained. I've done a PR two years ago but since that I'm no longer working on jboss. 
If you want to fork please check all PR not merged.

**Comment by ymitsos** [comment]
Hi @sgargel, have already forked and implemented additional functionality. Not sure I understood your last sentence.

**Comment by sgargel** [comment]
Just a suggestion to maintain this project merging all PR pending :-)

**Comment by ymitsos** [comment]
@sgargel the major feature that must be addressed is the support of JBoss clustering and not only standalone version. Will see.
